repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Version de Ruff à utiliser
    rev: v0.1.6
    hooks:
    # Linting
    -   id: ruff
        args: [ --fix ]
    # Formatting
    -   id: ruff-format 